### ISSUE TITLE
Monsoon every few minutes fails to provide data & takes 30+ seconds to respond

### ISSUE THREAD

**Issue by jmessenger51** [STORDIS/monsoon#53]
We have ~20 SONiC switches running Broadcom Enterprise sonic.  All of them are running the latest 1.1.0 monsoon container.  The issue we are seeing is every few minutes the container appears to hang for 30+ seconds. Prometheus attempts to scrape the page and fails which generates alerts.

What would cause the container to hang for 30+ seconds?  Per docker there are no restart events for the container, however the outage is very consistent.  Below are two images from Grafana that show the data gaps. Every switch and every data point has the same time gap, but only for the monsoon provided data.  Node Exporter and other exporters have clean lines without gaps.

![System uptime Data Gaps](https://github.com/STORDIS/monsoon/assets/59372273/3cad3c99-70d4-4a66-b005-f50ec89bce0d)

![Ethernet Frames Recieved - data gaps](https://github.com/STORDIS/monsoon/assets/59372273/3ef76013-4891-4a8b-9c35-8975c4548cd5)

**Comment by kamalkrbh** [comment]
Hi @jmessenger51 ,
Can you please check logs of sonic-exporter container.
Please check using command - docker logs -f sonic-exporter

In the logs you can ignore _/usr/bin/vtysh: line 11: sonic-cfggen: command not found_.  , Apart from this do see any DB connection issues or so?

**Comment by jmessenger51** [comment]
[2023-08-30 14:59:44,110][INFO][exporter.py:2537] Starting Python exporter server at 0.0.0.0:9101
[2023-08-30 15:00:29,189][INFO][exporter.py:236] SONiC System is ready.
/usr/bin/vtysh: line 11: sonic-cfggen: command not found
/usr/bin/vtysh: line 11: sonic-cfggen: command not found
[2023-08-30 15:01:08,390][INFO][exporter.py:2537] Starting Python exporter server at 0.0.0.0:9101
[2023-08-30 15:02:01,471][INFO][exporter.py:236] SONiC System is ready.
/usr/bin/vtysh: line 11: sonic-cfggen: command not found
/usr/bin/vtysh: line 11: sonic-cfggen: command not found
/usr/bin/vtysh: line 11: sonic-cfggen: command not found
/usr/bin/vtysh: line 11: sonic-cfggen: command not found
/usr/bin/vtysh: line 11: sonic-cfggen: command not found
/usr/bin/vtysh: line 11: sonic-cfggen: command not found
/usr/bin/vtysh: line 11: sonic-cfggen: command not found
/usr/bin/vtysh: line 11: sonic-cfggen: command not found
/usr/bin/vtysh: line 11: sonic-cfggen: command not found
/usr/bin/vtysh: line 11: sonic-cfggen: command not found
/usr/bin/vtysh: line 11: sonic-cfggen: command not found
/usr/bin/vtysh: line 11: sonic-cfggen: command not found
[2023-08-30 15:04:22,169][INFO][exporter.py:2537] Starting Python exporter server at 0.0.0.0:9101
[2023-08-30 15:05:07,245][INFO][exporter.py:236] SONiC System is ready.

**Comment by kamalkrbh** [comment]
@jmessenger51 , In the logs it looks sonic-exporter has been restarted several times, almost every minute, Is it intentional ?
You were also mentioning that data gaps are consistent, is there any scheduled outage or cron jobs configured to turn-off devices/processes ?

**Comment by jmessenger51** [comment]
no cron job, the container should run continuously.  The only reason it should stop is if the container failed and docker restarts the container.

**Comment by jmessenger51** [comment]
Updated prometheus to query the exporter once every minute with a timeout of 1.5 minutes.  Also installed new sonic-exporter (1.1.0) and node-exporter (1.6.1) and I'm now only seeing data gaps on 3 out of 20 switches. Those devices are running a diffrent version of sonic.
